# Generated by Django 4.2.4 on 2023-10-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='femartist',
            old_name='name',
            new_name='fname',
        ),
    ]
