# Generated by Django 4.2.4 on 2023-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('album', models.ManyToManyField(to='new_model.album')),
                ('artist', models.ManyToManyField(to='new_model.artist')),
                ('fArtist', models.ManyToManyField(to='new_model.femartist')),
            ],
        ),
    ]
